development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: tech2me_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: tech2me_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: tech2me_production
  pool: 5